# Generated by Django 2.0.5 on 2021-10-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_officer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_details',
            name='gender',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station_details',
            name='police_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
