# Generated by Django 2.0.5 on 2021-10-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_officer', '0002_auto_20211012_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_details',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
