# Generated by Django 2.0.5 on 2021-10-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higher_officer', '0003_station_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_details',
            name='area_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station_details',
            name='password',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station_details',
            name='userid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
