# Generated by Django 2.0.5 on 2021-10-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='criminal_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=300)),
                ('arae_code', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('criminal_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('complaint_type', models.CharField(max_length=200)),
                ('acts', models.CharField(max_length=200)),
                ('sessions', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('criminal_image', models.FileField(upload_to='')),
            ],
        ),
    ]
