# Generated by Django 2.0.5 on 2021-10-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_complaints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('area_code', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('complaint_type', models.CharField(max_length=200)),
                ('complaint', models.CharField(max_length=200)),
            ],
        ),
    ]
