# Generated by Django 2.0.5 on 2021-10-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_complaints',
            name='complaint_status',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
